### ISSUE TITLE
Windows版本,無法正常開啟

### ISSUE THREAD

**Issue by kys20548** [jackychu0830/jy-srt-tools#1]
![73875](https://user-images.githubusercontent.com/32809060/124009573-5b3d2d80-da10-11eb-88ea-27dacb14cc89.jpg)

這邊先謝謝大神無私的分享,上面是我執行時出現的錯誤,不知道能給您參考看看嗎？
以下是我的jdk版本
![73876](https://user-images.githubusercontent.com/32809060/124009800-9ccdd880-da10-11eb-9b0c-d9f45770aade.jpg)

感激不盡😭

**Comment by jackychu0830** [comment]
你在看到這個錯誤訊息前，沒有任何錯誤畫面跳出來嗎？像是「開啟草稿檔案錯誤!」或「分析草稿內容錯誤!」
另外請問你的剪映版本是多少？

**Comment by jackychu0830** [comment]
這個錯誤在最新版本的工具已經排除
在執行工具箱之前，請先在剪映裡最少新增一個影片草稿檔
