### ISSUE TITLE
由.srt產生draft_content.json

### ISSUE THREAD

**Issue by emisjerry** [jackychu0830/jy-srt-tools#2]
Hi, 你的工具幫了很多忙，感謝你的分享。

因為剪映的字幕修改沒有像Subtitle Edit、Aegisub等專業工具方便，在語音辨識並匯出srt檔後，我會先用Subtitle Edit逐句修改，再將修改後的srt上傳到YouTube。

這樣的流程可惜的是沒辦法在剪映裡讀取修改後的內容，以產生內嵌字幕的影片。

不知是否能再提供讀取.srt檔，再產生出draft_content.json的功能?

**Comment by jackychu0830** [comment]
是的，你說的沒錯，剪映編輯字幕的功能很難用
所以我也是匯出 srt 檔後，使用 ArcTime Pro 這個軟體來編輯字幕
ArcTime Pro 可以把影片和字幕嵌在一起輸出，很方便

關於匯入 srt 字幕，之前也有人問過，我找時間研究一下，應該是可以逆推回去的

Thanks,
Jacky

**Comment by emisjerry** [comment]
感謝回覆。

我有錄了一個介紹工具箱的影片：https://youtu.be/6A31mrbtpVU

希望有更多朋友使用你的作品。

**Comment by jackychu0830** [comment]
哇~~ 好感動喔！居然還錄影片介紹~~ 謝謝支持啊!!

**Comment by jackychu0830** [comment]
已經有匯入 SRT 的功能，而且可以直接在工具箱裡編輯字幕
