### ISSUE TITLE
运行不了啊

### ISSUE THREAD

**Issue by zhouhao27** [jackychu0830/jy-srt-tools#3]
安装了JRE 11，然后运行，错误信息如下：

> Java Application launch failed

> Check Console for possible error messages related to "/Application/jy-srt-tools-2.3.251-Mac.jar".

**Comment by jackychu0830** [comment]
你先執行 terminal
<img width="316" alt="Screen Shot 2022-04-05 at 8 20 03 PM" src="https://user-images.githubusercontent.com/3303377/161889472-7a85ea24-e72a-43be-ab1a-40e99436cb6e.png">

然後輸入以下指令 (假設你把下載後的工具箱放在 Downloads 目錄下, 如果不是，請把指令換成正確的路徑)
java -jar ~/Downloads/jy-srt-tools-2.3.251-Mac.jar
<img width="975" alt="Screen Shot 2022-04-05 at 8 21 04 PM" src="https://user-images.githubusercontent.com/3303377/161889639-e4a200fd-d9dd-4908-9532-daa8489adfaa.png">

然後再告訴我錯誤訊息是什麼, 謝謝
