### ISSUE TITLE
配置java环境都不说吗？直接点击jar文件根本打不开。

### ISSUE THREAD

**Issue by yufanme** [jackychu0830/jy-srt-tools#4]

**Comment by jackychu0830** [comment]
不需要配置啊，我的影片裡很清楚，直接安裝Java 執行環境後，就可以執行 jar 檔了
如果左鍵點兩下不行，可以按滑鼠右鍵，再選擇開啟，試試看
![open](https://user-images.githubusercontent.com/3303377/161888692-3165bf93-3945-4927-a653-092ee81da7b7.png)

**Comment by yufanme** [comment]
我网上搜了一些，要用命令行cd到文件夹，再用java命令才行，直接打开没反应。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jacky ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 中午11:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jackychu0830/jy-srt-tools] 配置java环境都不说吗？直接点击jar文件根本打不开。 (Issue #4)





 
不需要配置啊，我的影片裡很清楚，直接安裝Java 執行環境後，就可以執行 jar 檔了
 如果左鍵點兩下不行，可以按滑鼠右鍵，再選擇開啟，試試看

**Comment by jackychu0830** [comment]
執行 Java Application 有三種方式
1. 最簡單的就是滑鼠左鍵點兩下開啟
2. 按滑鼠右鍵，再選擇開啟 (如上圖)
3. 最麻煩的就是你遇到的狀況，請看 https://github.com/jackychu0830/jy-srt-tools/issues/3

因為每個人的電腦設定不同，安裝了不少軟體，所以遇到的狀況也不盡相同
第3種方式是一定可以開啟的，但就比較麻煩些
