### ISSUE TITLE
新版本剪映2.9导出失效了

### ISSUE THREAD

**Issue by zhouxuan3550** [jackychu0830/jy-srt-tools#5]
现在的2.9版本导出失效了，全是乱码，吸收作者更新下呀，还有如果可以有简体中文的界面就更好啦，现在繁体看着有点迷糊

**Comment by jackychu0830** [comment]
我找不到2.9 版可以下載，官網最新也只到2.8.5

**Comment by jackychu0830** [comment]
就幾個按鈕而已，用幾次就熟悉了
而且這是簡轉繁的工具啊! 一堆字幕轉成繁體不就更看不懂 :P

**Comment by jackychu0830** [comment]
已更新 工具箱 Mac 版到 [2.3.290](https://github.com/jackychu0830/jy-srt-tools/releases/download/2.3.290-Mac/jy-srt-tools-2.3.290-Mac.jar)

**Comment by zhouxuan3550** [comment]
感觉大佬



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jacky Chu ***@***.***&gt;
发送时间: 2022年4月17日 13:46
收件人: jackychu0830/jy-srt-tools ***@***.***&gt;
抄送: zhouxuan3550 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jackychu0830/jy-srt-tools] 新版本剪映2.9导出失效了 (Issue #5)





 
已更新 工具箱 Mac 版到 2.3.290
