### ISSUE TITLE
新版

### ISSUE THREAD

**Issue by gabbyx492** [jackychu0830/jy-srt-tools#6]
你好喔。目前剪映測試版mac 多了字幕的顏色字型Jianying_2_9_5-beta2_6237_beta

等等的設定。所以整個都亂掉了。 期待作者出新版工具。感謝

**Comment by jackychu0830** [comment]
已更新 工具箱 Mac 版到 [2.3.290](https://github.com/jackychu0830/jy-srt-tools/releases/download/2.3.290-Mac/jy-srt-tools-2.3.290-Mac.jar)
