### ISSUE TITLE
英文字幕

### ISSUE THREAD

**Issue by hiiwii** [jackychu0830/jy-srt-tools#7]
可以读取英文字幕的时间戳，但读不到内容，不知道其他人有没有同样的问题。

**Comment by jackychu0830** [comment]
剪映可以自動生成英文字幕？不是很了解你的問題，可以詳細說明嗎？

**Comment by hiiwii** [comment]
Jacky 您好

        我昨天打开了一个老的英文档案，读取后其他列都有信息，包括时间戳，但是字幕那一列是空的，同时昨天打开中文档案是正常的，后来那个英文档案被我删除了。看到您的回复，我今天新建了一个英文档案，进行语音识别，读取后是正常的。可能还是老档案本身的问题。不好意思。



***@***.***
 
发件人： Jacky Chu
发送时间： 2022-04-23 01:24
收件人： jackychu0830/jy-srt-tools
抄送： hiiwii; Author
主题： Re: [jackychu0830/jy-srt-tools] 英文字幕 (Issue #7)
剪映可以自動生成英文字幕？不是很了解你的問題，可以詳細說明嗎？

**Comment by jackychu0830** [comment]
那我猜應該是舊版剪映的草稿檔，無法用新版的工具箱正常讀取，所以常常剪映一改版，如果字幕格式有更動，我也得修改工具箱，再請大家下載
