### ISSUE TITLE
最新版無法執行

### ISSUE THREAD

**Issue by caryn1021** [jackychu0830/jy-srt-tools#8]
你好，我是windows使用者，請問最新版的程序是在哪裏呢？
雙擊打開後是這樣的
![image](https://user-images.githubusercontent.com/104887157/166631650-672d8faf-0daa-4d53-a38e-1f1ab98c8e63.png)

舊版沒問題因爲打開后就看到程序了，雙擊就能執行
![image](https://user-images.githubusercontent.com/104887157/166631805-4470afdb-7af8-4bb3-a517-ccadb3f72195.png)

**Comment by jackychu0830** [comment]
因為你的解壓縮程式把 jar 檔當壓縮檔了，所以會自動解開
你照這三種方式看看能不能執行
https://github.com/jackychu0830/jy-srt-tools/issues/4#issuecomment-1093220812

**Comment by caryn1021** [comment]
我找到方法打開了，按右鍵然後open with OpenJDK就能執行了
謝謝大神~
